services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2182:2181"  # Changed from 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9094:9092"  # Changed from 9092

  order-service:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - ./order-service:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "pip install flask==2.3.3 kafka-python==2.0.2 && python app.py"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092

  inventory-service:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - ./inventory-service:/app
    ports:
      - "8001:8001"
    command: >
      sh -c "pip install flask==2.3.3 kafka-python==2.0.2 && python app.py"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092