apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-simulator
  namespace: realtime-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-simulator
  template:
    metadata:
      labels:
        app: user-simulator
    spec:
      containers:
      - name: user-simulator
        image: yourusername/user-simulator:latest  # Replace with your image
        env:
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-simulator
  namespace: realtime-analytics
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: user-simulator