global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    
  - job_name: 'user-simulator'
    static_configs:
      - targets: ['user-simulator:8000']