# user-simulator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-simulator
  namespace: realtime-analytics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-simulator
  template:
    metadata:
      labels:
        app: user-simulator
    spec:
      containers:
      - name: user-simulator
        image: user-simulator:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_BOOTSTRAP_SERVERS
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-simulator-service
  namespace: realtime-analytics
spec:
  selector:
    app: user-simulator
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP